# GET http://localhost:5000/api/posts?page=1&limit=10 


GET http://localhost:5000/api/donations?page=1&limit=3 


GET http://localhost:5000/api/volunteersInfo?page=1&limit=1


# https://capstone-project-annashakti-backend.onrender.com/api/